[project]
name = "langbench"
version = "0.1.0"
description = "Benchmark suite for sorting algorithms"
requires-python = ">=3.13"
dependencies = [
    "interpreters-pep-734==0.5.0",
]

[project.scripts]
langbench-st-mergesort = "st_mergesort:main"
langbench-mt-mergesort = "mt_mergesort:main"
